import axios from 'axios';

// require('dotenv').config()

// const apiUrl = process.env.BASE_BACKEND_API_URL;
// console.log(apiUrl);


// const instance = axios.create({
//     baseURL: apiUrl,
//     timeout: 1000,
// });

const fetch = (url, {...params}) => {
    axios.get(url)
        .then(function (response) {
            // handle success
            // console.log(response.data);
            return response.data;
        })
        .catch(function (error) {
            // handle error
            // console.log(error);
            return error;
        })
        .then(function () {
            // always executed
            // console.log('Api Get Request: ', url)
        });
}

// const groups = fetch("http://localhost:10500/api/v2/groups/");
// const users = fetch("http://localhost:10500/api/v2/users/");
const brands = fetch("http://localhost:10500/api/v2/brands/");
const carouselImages = fetch("http://localhost:10500/api/v2/carousel-images/");
const carousels = fetch("http://localhost:10500/api/v2/carousels/");
const categories = fetch("http://localhost:10500/api/v2/categories/");
const colors = fetch("http://localhost:10500/api/v2/colors/");
const comments = fetch("http://localhost:10500/api/v2/comments/");
const departments = fetch("http://localhost:10500/api/v2/departments/");
const lines = fetch("http://localhost:10500/api/v2/lines/");
const pagePositions = fetch("http://localhost:10500/api/v2/page-positions/");
const pages = fetch("http://localhost:10500/api/v2/pages/");
const posts = fetch("http://localhost:10500/api/v2/posts/");
const products = fetch("http://localhost:10500/api/v2/products/");
const providers = fetch("http://localhost:10500/api/v2/providers/");
const services = fetch("http://localhost:10500/api/v2/services/");
const site = fetch("http://localhost:10500/api/v2/site/");
const socialMedia = fetch("http://localhost:10500/api/v2/social-media/");
const subLines = fetch("http://localhost:10500/api/v2/sub-lines/");
const types = fetch("http://localhost:10500/api/v2/types/");
const testimonials = fetch("http://localhost:10500/api/v2/testimonials/");


const data = {
    blog_comments: comments,
    blog_post: posts,
    brands: brands,
    carrousel: carousels,
    colors: colors,
    categories: categories,
    departments: departments,
    img_carrousel: carouselImages,
    lines: lines,
    page_position: pagePositions,
    pages: pages,
    products: products,
    providers: providers,
    services: services,
    site: site,
    social_media: socialMedia,
    sub_lines: subLines,
    testimonials: testimonials,
    types: types,
    // users: users,
    user: {
        id: 0,
        token: null,
        last_login: null,
        is_superuser: false,
        username: "Guest",
        first_name: "",
        last_name: "",
        email: null,
        is_staff: false,
        is_active: false,
        date_joined: null
    },
}

export default data;

// const data = {
//     users: {
//         count: 14,
//         next: null,
//         previous: null,
//         results: [
//             {
//                 id: 24,
//                 token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyNCwidXNlcm5hbWUiOiIyMDE4NTUyMiIsImV4cCI6MTUzNTY5NDA4MiwiZW1haWwiOiJoc2hAZGV2MnRlY2gueHl6In0.MllXW6eLgblSlf9cTRkBrhF7W0JLGAqvI2cLqmJ9EiI",
//                 last_login: null,
//                 is_superuser: false,
//                 username: "20185522",
//                 first_name: "",
//                 last_name: "",
//                 email: "hsh@dev2tech.xyz",
//                 is_staff: false,
//                 is_active: false,
//                 date_joined: "2018-08-27T22:54:05.455997-05:00"
//             },
//             {
//                 id: 23,
//                 token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyMywidXNlcm5hbWUiOiJhZG1pbjAwIiwiZXhwIjoxNTM1Njk0MDgyLCJlbWFpbCI6Impvc21lcmFkbWluQGRldjJ0ZWNoLnh5eiJ9.CM4sLRDNXmmKY_1q7LPzZF8xPLAJvMA5o1BGM77EMVs",
//                 last_login: null,
//                 is_superuser: false,
//                 username: "admin00",
//                 first_name: "admin",
//                 last_name: "admin",
//                 email: "josmeradmin@dev2tech.xyz",
//                 is_staff: false,
//                 is_active: false,
//                 date_joined: "2018-08-27T22:53:11.317582-05:00"
//             },
//             {
//                 id: 22,
//                 token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyMiwidXNlcm5hbWUiOiI1NTU1NTU1NDU0NTQ1NCIsImV4cCI6MTUzNTY5NDA4MiwiZW1haWwiOiI1NUA1NS5jb20ifQ.Busijo1TOZr-xkkPuz5esIW5Aje2byINRcJGLsSrxJw",
//                 last_login: null,
//                 is_superuser: false,
//                 username: "55555554545454",
//                 first_name: "",
//                 last_name: "",
//                 email: "55@55.com",
//                 is_staff: false,
//                 is_active: true,
//                 date_joined: "2018-08-27T22:01:07.199816-05:00"
//             },
//             {
//                 id: 21,
//                 token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyMSwidXNlcm5hbWUiOiIxMjMiLCJleHAiOjE1MzU2OTQwODIsImVtYWlsIjoiampAZGV2MnRlY2gueHl6In0.ot8te9WPsHfiKsqZhzkTeHjJw-KceRQqRnifFPWzS60",
//                 last_login: null,
//                 is_superuser: true,
//                 username: "123",
//                 first_name: "",
//                 last_name: "",
//                 email: "jj@dev2tech.xyz",
//                 is_staff: false,
//                 is_active: false,
//                 date_joined: "2018-08-07T01:25:46.334516-05:00"
//             },
//             {
//                 id: 20,
//                 token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyMCwidXNlcm5hbWUiOiI3NDIyNDAwIiwiZXhwIjoxNTM1Njk0MDgyLCJlbWFpbCI6IiJ9.f_ga0L-vNzNYSL7A-BoHK2WqtSuXleapolhW5maMIVw",
//                 last_login: null,
//                 is_superuser: false,
//                 username: "7422400",
//                 first_name: "",
//                 last_name: "",
//                 email: "",
//                 is_staff: false,
//                 is_active: false,
//                 date_joined: "2018-08-07T01:25:42.613191-05:00"
//             },
//             {
//                 id: 19,
//                 token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxOSwidXNlcm5hbWUiOiI3IiwiZXhwIjoxNTM1Njk0MDgyLCJlbWFpbCI6IiJ9.kJENjO6XwO446YYwaRq5bn6Q2kXcBYLY1O-WYfmN0Y0",
//                 last_login: null,
//                 is_superuser: false,
//                 username: "7",
//                 first_name: "",
//                 last_name: "",
//                 email: "",
//                 is_staff: false,
//                 is_active: false,
//                 date_joined: "2018-08-07T01:25:21.590471-05:00"
//             },
//             {
//                 id: 18,
//                 token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxOCwidXNlcm5hbWUiOiIwMDIyMTA1MjQyNDAiLCJleHAiOjE1MzU2OTQwODIsImVtYWlsIjoiIn0.cUMV8CJq9iT4s6Khx0MR2cHT1tcv6WAbQ9vOcUrGUzk",
//                 last_login: null,
//                 is_superuser: false,
//                 username: "002210524240",
//                 first_name: "",
//                 last_name: "",
//                 email: "",
//                 is_staff: false,
//                 is_active: false,
//                 date_joined: "2018-08-07T01:25:15.273769-05:00"
//             },
//             {
//                 id: 17,
//                 token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxNywidXNlcm5hbWUiOiIwMDIyMSIsImV4cCI6MTUzNTY5NDA4MiwiZW1haWwiOiIifQ.TWApRmik14wT4RSgWgJCskcVZD29tyU_k6ug9aRvRjo",
//                 last_login: null,
//                 is_superuser: false,
//                 username: "00221",
//                 first_name: "",
//                 last_name: "",
//                 email: "",
//                 is_staff: false,
//                 is_active: false,
//                 date_joined: "2018-08-07T01:25:09.414297-05:00"
//             },
//             {
//                 id: 16,
//                 token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxNiwidXNlcm5hbWUiOiJqaGVybmFuZGV6LjE4cEBkZXYydGVjaC54eXoiLCJleHAiOjE1MzU2OTQwODIsImVtYWlsIjoiIn0.8G3soQyY_CP8WqZI4uoxOcrw4AW4txOCBxdmASjTQj8",
//                 last_login: null,
//                 is_superuser: false,
//                 username: "jhernandez.18p@dev2tech.xyz",
//                 first_name: "",
//                 last_name: "",
//                 email: "",
//                 is_staff: false,
//                 is_active: false,
//                 date_joined: "2018-08-07T01:24:50.745064-05:00"
//             },
//             {
//                 id: 15,
//                 token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxNSwidXNlcm5hbWUiOiJqb3NtZXIiLCJleHAiOjE1MzU2OTQwODIsImVtYWlsIjoiamhlcm5hbmRlei4xOHBAZGV2MnRlY2gueHl6LmNvbSJ9.cRebYb_9LAteEQxktIK2luo6SB4bd-YAo9GLRUb3y54",
//                 last_login: null,
//                 is_superuser: false,
//                 username: "josmer",
//                 first_name: "",
//                 last_name: "",
//                 email: "jhernandez.18p@dev2tech.xyz.com",
//                 is_staff: false,
//                 is_active: true,
//                 date_joined: "2018-08-07T01:14:31.266455-05:00"
//             },
//             {
//                 id: 13,
//                 token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMywidXNlcm5hbWUiOiJqaGVybmFuZGV6LjE4cDIiLCJleHAiOjE1MzU2OTQwODIsImVtYWlsIjoiamhlcm5hbmRlei4xOHBAZ21haWwuY29tIn0.1CAm8INQucIje4FZoNYjQa0P2VbKU9CKTYK6jjuXgKk",
//                 last_login: "2018-05-07T06:18:17.045781-05:00",
//                 is_superuser: false,
//                 username: "jhernandez.18p2",
//                 first_name: "Josmer",
//                 last_name: "Hernández",
//                 email: "jhernandez.18p@gmail.com",
//                 is_staff: false,
//                 is_active: true,
//                 date_joined: "2018-05-07T06:10:59.312323-05:00"
//             },
//             {
//                 id: 2,
//                 token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJ1c2VybmFtZSI6ImFkbWluIiwiZXhwIjoxNTM1Njk0MDgyLCJlbWFpbCI6ImpoZXJuYW5kZXouMThwQGdtYWlsLnRlc3QifQ.Y8cKyKGDcLwrU91uw1qPexScsv0AVqVPjfojJ8reDc8",
//                 last_login: "2018-02-27T13:00:14.461000-06:00",
//                 is_superuser: true,
//                 username: "admin",
//                 first_name: "Josmer",
//                 last_name: "Hernández",
//                 email: "jhernandez.18p@gmail.test",
//                 is_staff: true,
//                 is_active: true,
//                 date_joined: "2018-02-26T13:34:11-06:00"
//             },
//             {
//                 id: 1,
//                 token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6ImpoZXJuYW5kZXouMThwIiwiZXhwIjoxNTM1Njk0MDgyLCJlbWFpbCI6ImpoZXJuYW5kZXouMThwQGRldjJ0ZWNoLnh5eiJ9.zASGuu9usCtaiaxAM7PgdtM4rxZzRTfKj06cR59Drbk",
//                 last_login: "2018-08-28T05:25:12.777200-05:00",
//                 is_superuser: true,
//                 username: "jhernandez.18p",
//                 first_name: "Josmer",
//                 last_name: "Hernandez",
//                 email: "jhernandez.18p@dev2tech.xyz",
//                 is_staff: true,
//                 is_active: true,
//                 date_joined: "2018-02-26T13:23:53-06:00"
//             },
//             {
//                 id: 6,
//                 token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo2LCJ1c2VybmFtZSI6ImVkaXRvciIsImV4cCI6MTUzNTY5NDA4MiwiZW1haWwiOiJpbmZvQG1vYnktZ3JvdXAuY29tIn0.Uhz-2VoxLzxghaxug4jYdsaUh8oPVKQBYQZ75zabvog",
//                 last_login: "2018-02-24T23:57:19-06:00",
//                 is_superuser: false,
//                 username: "editor",
//                 first_name: "",
//                 last_name: "",
//                 email: "info@moby-group.com",
//                 is_staff: true,
//                 is_active: true,
//                 date_joined: "2018-02-24T23:57:18-06:00"
//             }
//         ]
//     },
//     img_carrousel:{
//         "count": 7,
//         "next": null,
//         "previous": null,
//         "results": [
//             {
//                 "id": 2,
//                 "image": "http://localhost:10500/media/frontend/carouselimage/2018/03/06/pexels-photo-198305.jpeg",
//                 "name": "Conozca nuestros productos",
//                 "text": "",
//                 "uploaded_at": "2018-03-06T11:49:27.706527-06:00",
//                 "Carousel": 2,
//                 "call_to_action_url": null
//             },
//             {
//                 "id": 3,
//                 "image": "http://localhost:10500/media/frontend/carouselimage/2018/03/06/pexels-photo-196599.jpeg",
//                 "name": "Header Products 01",
//                 "text": "<p>Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>",
//                 "uploaded_at": "2018-03-06T11:49:27.715553-06:00",
//                 "Carousel": 2,
//                 "call_to_action_url": null
//             },
//             {
//                 "id": 4,
//                 "image": "http://localhost:10500/media/frontend/carouselimage/2018/03/06/AdobeStock_83839997.jpeg",
//                 "name": "Header Products 02",
//                 "text": "<p>Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>",
//                 "uploaded_at": "2018-03-06T11:49:27.729936-06:00",
//                 "Carousel": 2,
//                 "call_to_action_url": null
//             },
//             {
//                 "id": 5,
//                 "image": "http://localhost:10500/media/frontend/carouselimage/2018/03/15/img-base-m_RjeCg9w.png",
//                 "name": "Imagen 02",
//                 "text": "",
//                 "uploaded_at": "2018-03-15T02:04:29.049064-05:00",
//                 "Carousel": 1,
//                 "call_to_action_url": null
//             },
//             {
//                 "id": 1,
//                 "image": "http://localhost:10500/media/frontend/carouselimage/2018/03/15/img-base-m.png",
//                 "name": "Bienvenidos a Moby Supply",
//                 "text": "",
//                 "uploaded_at": "2018-05-05T10:28:48.677397-05:00",
//                 "Carousel": 1,
//                 "call_to_action_url": 5
//             },
//             {
//                 "id": 6,
//                 "image": "http://localhost:10500/media/carouselimage/2018/09/03/pexels-photo-27117.jpg",
//                 "name": "test",
//                 "text": "",
//                 "uploaded_at": "2018-09-03T23:05:53.620469-05:00",
//                 "Carousel": 1,
//                 "call_to_action_url": null
//             },
//             {
//                 "id": 7,
//                 "image": "http://localhost:10500/media/carouselimage/2018/09/03/JM-Industrial-800_1893.jpg",
//                 "name": "Imagen 01",
//                 "text": "",
//                 "uploaded_at": "2018-09-03T23:17:45.444716-05:00",
//                 "Carousel": 3,
//                 "call_to_action_url": null
//             }
//         ]
//     },
//     carrousel:{
//         count: 2,
//         next: null,
//         previous: null,
//         results: [
//             {
//                 id: 2,
//                 page: 3,
//                 position: 1,
//                 images: [
//                     2,
//                     3,
//                     4
//                 ],
//                 name: "Header carousel productos",
//                 description: "",
//                 crated_at: "2018-03-06T11:49:27.641237-06:00"
//             },
//             {
//                 id: 1,
//                 page: 1,
//                 position: 1,
//                 images: [
//                     5,
//                     1
//                 ],
//                 name: "Header carousel home",
//                 description: "<p>Header del home</p>",
//                 crated_at: "2018-05-05T10:28:48.676395-05:00"
//             }
//         ]
//     },
//     blog_comments: {
//         count: 16,
//         next: null,
//         previous: null,
//         results: [
//             {
//                 id: 17,
//                 content: "<p>iuityuitytyu7</p>",
//                 approved: true,
//                 timestamp: "2018-03-10T01:21:04.465295-06:00",
//                 object_id: 1,
//                 author: 1,
//                 parent: null,
//                 post: 1,
//                 content_type: 17
//             },
//             {
//                 id: 16,
//                 content: "<p>comentario 02</p>",
//                 approved: true,
//                 timestamp: "2018-03-09T16:00:15.658750-06:00",
//                 object_id: 4,
//                 author: 1,
//                 parent: null,
//                 post: 4,
//                 content_type: 17
//             },
//             {
//                 id: 15,
//                 content: "<p>comentario 01</p>",
//                 approved: true,
//                 timestamp: "2018-03-09T16:00:01.476977-06:00",
//                 object_id: 4,
//                 author: 1,
//                 parent: null,
//                 post: 4,
//                 content_type: 17
//             },
//             {
//                 id: 14,
//                 content: "<p>s</p>",
//                 approved: true,
//                 timestamp: "2018-03-08T06:51:56.640432-06:00",
//                 object_id: 4,
//                 author: 1,
//                 parent: null,
//                 post: 4,
//                 content_type: 17
//             },
//             {
//                 id: 13,
//                 content: "<p>test</p>",
//                 approved: true,
//                 timestamp: "2018-03-02T00:05:22.861598-06:00",
//                 object_id: 1,
//                 author: 1,
//                 parent: null,
//                 post: 1,
//                 content_type: 17
//             },
//             {
//                 id: 1,
//                 content: "<p>este es un comentario</p>",
//                 approved: true,
//                 timestamp: "2018-02-27T10:21:41.507000-06:00",
//                 object_id: 1,
//                 author: 2,
//                 parent: null,
//                 post: 1,
//                 content_type: 17
//             },
//             {
//                 id: 11,
//                 content: "<table border=\"1\" cellpadding=\"1\" cellspacing=\"1\" style=\"width:500px\">\r\n\t<tbody>\r\n\t\t<tr>\r\n\t\t\t<td>&nbsp;</td>\r\n\t\t\t<td>&nbsp;</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td>&nbsp;</td>\r\n\t\t\t<td>&nbsp;</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td>&nbsp;</td>\r\n\t\t\t<td>&nbsp;</td>\r\n\t\t</tr>\r\n\t</tbody>\r\n</table>\r\n\r\n<p>&nbsp;</p>",
//                 approved: true,
//                 timestamp: "2018-02-24T21:44:07.392880-06:00",
//                 object_id: 2,
//                 author: 1,
//                 parent: null,
//                 post: 2,
//                 content_type: 17
//             },
//             {
//                 id: 10,
//                 content: "<p><img alt=\"wink\" src=\"http://localhost:10500/static/ckeditor/ckeditor/plugins/smiley/images/wink_smile.png\" style=\"height:23px; width:23px\" title=\"wink\" /></p>",
//                 approved: true,
//                 timestamp: "2018-02-24T21:43:48.084651-06:00",
//                 object_id: 2,
//                 author: 1,
//                 parent: null,
//                 post: 2,
//                 content_type: 17
//             },
//             {
//                 id: 9,
//                 content: "<p><img alt=\"\" src=\"https://static.pexels.com/photos/890710/pexels-photo-890710.jpeg\" /></p>",
//                 approved: true,
//                 timestamp: "2018-02-24T21:40:12.196545-06:00",
//                 object_id: 2,
//                 author: 1,
//                 parent: null,
//                 post: 2,
//                 content_type: 17
//             },
//             {
//                 id: 8,
//                 content: "<hr />\r\n<hr />\r\n<hr />\r\n<hr />\r\n<p>&nbsp;</p>",
//                 approved: true,
//                 timestamp: "2018-02-24T21:39:31.264931-06:00",
//                 object_id: 2,
//                 author: 1,
//                 parent: null,
//                 post: 2,
//                 content_type: 17
//             },
//             {
//                 id: 7,
//                 content: "<p>Nuevo comentario</p>",
//                 approved: true,
//                 timestamp: "2018-02-24T21:33:57.269255-06:00",
//                 object_id: 2,
//                 author: 1,
//                 parent: null,
//                 post: 2,
//                 content_type: 17
//             },
//             {
//                 id: 6,
//                 content: "<p>fl lkjvm lvr</p>",
//                 approved: true,
//                 timestamp: "2018-02-23T13:01:15.906828-06:00",
//                 object_id: 2,
//                 author: 1,
//                 parent: null,
//                 post: 2,
//                 content_type: 17
//             },
//             {
//                 id: 5,
//                 content: "<p>ssss</p>",
//                 approved: true,
//                 timestamp: "2018-02-23T13:00:07.910510-06:00",
//                 object_id: 2,
//                 author: 1,
//                 parent: null,
//                 post: 2,
//                 content_type: 17
//             },
//             {
//                 id: 4,
//                 content: "<p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Non quisquam numquam perferendis earum sit error quae ad blanditiis at, corporis assumenda, rerum magnam explicabo est, pariatur adipisci sapiente deserunt soluta?</p>",
//                 approved: false,
//                 timestamp: "2018-02-16T06:23:19.778778-06:00",
//                 object_id: 3,
//                 author: 1,
//                 parent: null,
//                 post: 3,
//                 content_type: 17
//             },
//             {
//                 id: 3,
//                 content: "<p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Non quisquam numquam perferendis earum sit error quae ad blanditiis at, corporis assumenda, rerum magnam explicabo est, pariatur adipisci sapiente deserunt soluta?</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Non quisquam numquam perferendis earum sit error quae ad blanditiis at, corporis assumenda, rerum magnam explicabo est, pariatur adipisci sapiente deserunt soluta?</p>",
//                 approved: true,
//                 timestamp: "2018-02-16T05:42:31.763641-06:00",
//                 object_id: 3,
//                 author: 1,
//                 parent: null,
//                 post: 3,
//                 content_type: 17
//             },
//             {
//                 id: 2,
//                 content: "<p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Non quisquam numquam perferendis earum sit error quae ad blanditiis at, corporis assumenda, rerum magnam explicabo est, pariatur adipisci sapiente deserunt soluta?</p>\r\n\r\n<p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Non quisquam numquam perferendis earum sit error quae ad blanditiis at, corporis assumenda, rerum magnam explicabo est, pariatur adipisci sapiente deserunt soluta?</p>",
//                 approved: true,
//                 timestamp: "2018-02-16T05:41:19.538814-06:00",
//                 object_id: 2,
//                 author: 1,
//                 parent: null,
//                 post: 2,
//                 content_type: 17
//             }
//         ]
//     },
//     user: {
//         id: 0,
//         token: null,
//         last_login: null,
//         is_superuser: false,
//         username: "Guest",
//         first_name: "",
//         last_name: "",
//         email: null,
//         is_staff: false,
//         is_active: false,
//         date_joined: null
//     },
//     site: {
//         count: 1,
//         next: null,
//         previous: null,
//         results: [
//             {
//                 id: 1,
//                 name: 'Moby Supply',
//                 title: "Moby Supply",
//                 short_description: `Moby Panamá, S.A. fue fundada en Panamá en el año 2011 estructurada en forma sociedad anónima.
//                     Actualmente, con más de 30 colaboradores, hacemos presencia en Panamá.`,
//                 description: `Moby Panamá, S.A. fue fundada en Panamá en el año 2011. Actualmente, con más de 30 colaboradores, 
//                     una Fábrica y una Tienda ubicada en calle 1ra de Rio Abajo, nuestra base de productos y servicios se ve respaldada 
//                     con marcas reconocidas internacionalmente en el ramo ferretero-maderero como FGV, Grupo Losan, entre otras, cada 
//                     año hemos ido incrementando productos y presentando ofertas y soluciones para el sector.`,
//                 url: "https://www.mobby-group.com",
//                 phone: null,
//                 phone2: null,
//                 email: null,
//                 email2: null,
//                 schedule: "8:00 am - 5:00 pm <br> Sabados de 8:00 a 1:00 pm",
//                 workday: "Lunes a Viernes y sabados",
//                 address: null,
//                 address1: null,
//                 logo: "http://localhost:10500/media/static/base/img/moby.png",
//                 site_img: "http://localhost:10500/media/frontend/site/2018/03/09/img-base-m.png",
//                 services_img: "http://localhost:10500/media/frontend/site/2018/03/09/img-base-s.png",
//                 products_img: "http://localhost:10500/media/frontend/site/2018/03/09/img-base-s_SenI6S2.png",
//                 direction: 'Ernesto T. Lefevre, diagonal a Waikiki, Panama Panamá',
//                 direction_city: 'Ciudad de Panamá',
//                 is_undercostruction: false,
//             },
//         ]
//     },
//     social_media: {
//         count: 2,
//         next: null,
//         previous: null,
//         results: [
//             {
//                 id: 1,
//                 name: "Instagram",
//                 url: "https://www.instagram.com/mobysupply/",
//                 icon: "fa-instagram",
//                 title: "MobySupply",
//                 site: 1
//             },
//             {
//                 id: 2,
//                 name: "Facebook",
//                 url: "https://www.facebook.com/moby-supply",
//                 icon: "fa-facebook",
//                 title: "Facebook",
//                 site: 1
//             }
//         ]
//     },
//     services: {
//         count: 3,
//         next: null,
//         previous: null,
//         results: [
//             {
//                 id: 1,
//                 name: "Cortes",
//                 title: "Cortes",
//                 content: "<p>Servicio de corte</p>",
//                 slug: "cortes",
//                 image: "http://localhost:10500/media/sales/service/2018/03/09/img-base-m.png",
//                 background: "http://localhost:10500/media/sales/service/2018/03/09/img-base-l.png"
//             },
//             {
//                 id: 2,
//                 name: "Canteo",
//                 title: "Canteo",
//                 content: "<p>Servicio de canteo</p>",
//                 slug: "canteo",
//                 image: "http://localhost:10500/media/sales/service/2018/03/09/img-base-m_L3HyKsU.png",
//                 background: "http://localhost:10500/media/sales/service/2018/03/09/img-base-l_xMy0ppQ.png"
//             },
//             {
//                 id: 3,
//                 name: "Perforación",
//                 title: "Perforación",
//                 content: "<p>Servicio de Perforaci&oacute;n</p>",
//                 slug: "perforacion",
//                 image: "http://localhost:10500/media/sales/service/2018/03/09/img-base-m_vNZSASG.png",
//                 background: "http://localhost:10500/media/sales/service/2018/03/09/img-base-l_MOn9oRr.png"
//             }
//         ]
//     },
//     brands: {
//         count: 2,
//         next: null,
//         previous: null,
//         results: [
//             {
//                 id: 2,
//                 background: null,
//                 description: "<p>salice</p>",
//                 img: null,
//                 logo: null,
//                 name: "Salice",
//                 slug: "salice",
//                 website: "",
//                 code: "00002"
//             },
//             {
//                 id: 1,
//                 background: null,
//                 description: "<p>Moby</p>",
//                 img: "http://localhost:10500/media/sales/brands/2018/04/30/0om1b.png",
//                 logo: "http://localhost:10500/media/sales/brands/2018/04/30/y4042.png",
//                 name: "Moby Supply",
//                 slug: "moby-supply",
//                 website: "https://moby-group.com",
//                 code: "00001"
//             },
//         ]
//     },
//     products: {
//         count: 1080,
//         next: "http://localhost:10500/api/v2/article/?limit=20&offset=20",
//         previous: null,
//         results: [
//             {
//                 id: 1,
//                 code: "1010101.0",
//                 model: "a",
//                 name: "articulo 01",
//                 origin: "",
//                 sales_unit: "",
//                 ref: "",
//                 description: "<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis rerum accusamus fugit, nulla ex recusandae provident delectus illo, beatae velit dicta autem? Placeat vel iure molestiae. Illo recusandae labore explicabo.</p>",
//                 slug: "articulo-01-4",
//                 stock: 0,
//                 views: 0,
//                 picture: null,
//                 price_1: "1.00",
//                 price_2: "1.60",
//                 price_3: "2.56",
//                 price_4: "4.10",
//                 price_5: "6.55",
//                 updated: "2018-05-17T22:32:14.692901-05:00",
//                 created_at: "2018-02-27T10:11:36.590000-06:00",
//                 img: "http://localhost:10500/media/sales/arts/base.jpg",
//                 active: false,
//                 featured: false,
//                 imported: false,
//                 is_shipping_required: false,
//                 item_type: 1,
//                 line: 25,
//                 category: 99,
//                 color: 238,
//                 department: 3,
//                 brand: 1,
//                 provider: 1365,
//                 sub_line: 170
//             },
//             {
//                 id: 3235,
//                 code: "3030303.0",
//                 model: "d",
//                 name: "lorm",
//                 origin: "",
//                 sales_unit: "",
//                 ref: "",
//                 description: "<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem deserunt placeat fuga eligendi, quis, inventore sed dolores nemo, quod excepturi dolore! Vitae possimus, at distinctio soluta numquam ut facilis dignissimos.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem deserunt laceat fuga eligendi, quis, inventore sed dolores nemo, quod excepturi dolore! Vitae possimus, at distinctio soluta numquam ut facilis dignissimos.</p>",
//                 slug: "a-3234",
//                 stock: 0,
//                 views: 0,
//                 picture: null,
//                 price_1: "3.00",
//                 price_2: "4.80",
//                 price_3: "7.68",
//                 price_4: "12.29",
//                 price_5: "19.66",
//                 updated: "2018-05-17T22:32:14.692901-05:00",
//                 created_at: "2018-05-08T01:06:30.024420-05:00",
//                 img: "http://localhost:10500/media/sales/arts/base.jpg",
//                 active: false,
//                 featured: false,
//                 imported: false,
//                 is_shipping_required: false,
//                 item_type: 1,
//                 line: null,
//                 category: null,
//                 color: null,
//                 department: null,
//                 brand: 1,
//                 provider: null,
//                 sub_line: null
//             },
//             {
//                 id: 3302,
//                 code: "0113120",
//                 model: "",
//                 name: "",
//                 origin: "",
//                 sales_unit: "PZA",
//                 ref: "",
//                 description: "<p>CUBIERTERO LINEA TEN DE 450 MM</p>",
//                 slug: "0113120-3278",
//                 stock: 36,
//                 views: 0,
//                 picture: null,
//                 price_1: "7.20",
//                 price_2: "8.00",
//                 price_3: "9.20",
//                 price_4: "11.50",
//                 price_5: "9.20",
//                 updated: "2018-05-17T22:32:14.661659-05:00",
//                 created_at: "2018-05-08T12:22:07.455233-05:00",
//                 img: "http://localhost:10500/media/sales/arts/base.jpg",
//                 active: false,
//                 featured: false,
//                 imported: false,
//                 is_shipping_required: false,
//                 item_type: 1,
//                 line: null,
//                 category: null,
//                 color: null,
//                 department: null,
//                 brand: 1,
//                 provider: null,
//                 sub_line: null
//             },
//             {
//                 id: 5455,
//                 code: "0113120                       ",
//                 model: "                    ",
//                 name: "",
//                 origin: "",
//                 sales_unit: "PZA   ",
//                 ref: "                    ",
//                 description: "CUBIERTERO LINEA TEN DE 450 MM                                                                                          ",
//                 slug: "0113120",
//                 stock: 36,
//                 views: 0,
//                 picture: null,
//                 price_1: "7.20",
//                 price_2: "8.00",
//                 price_3: "9.20",
//                 price_4: "11.50",
//                 price_5: "9.20",
//                 updated: "2018-05-17T22:32:14.646045-05:00",
//                 created_at: "2018-05-08T15:28:46.015420-05:00",
//                 img: "http://localhost:10500/media/sales/arts/base.jpg",
//                 active: false,
//                 featured: false,
//                 imported: false,
//                 is_shipping_required: false,
//                 item_type: 1,
//                 line: null,
//                 category: null,
//                 color: null,
//                 department: null,
//                 brand: 1,
//                 provider: null,
//                 sub_line: 173
//             },
//             {
//                 id: 5456,
//                 code: "0113320                       ",
//                 model: "                    ",
//                 name: "",
//                 origin: "",
//                 sales_unit: "PZA   ",
//                 ref: "                    ",
//                 description: "CUBIERTERO LINEA TEN DE 600 MM                                                                                          ",
//                 slug: "0113320",
//                 stock: 4,
//                 views: 0,
//                 picture: null,
//                 price_1: "9.00",
//                 price_2: "10.00",
//                 price_3: "11.50",
//                 price_4: "14.38",
//                 price_5: "11.50",
//                 updated: "2018-05-17T22:32:14.646045-05:00",
//                 created_at: "2018-05-08T15:28:46.024960-05:00",
//                 img: "http://localhost:10500/media/sales/arts/base.jpg",
//                 active: false,
//                 featured: false,
//                 imported: false,
//                 is_shipping_required: false,
//                 item_type: 1,
//                 line: null,
//                 category: null,
//                 color: null,
//                 department: null,
//                 brand: 1,
//                 provider: null,
//                 sub_line: 173
//             },
//             {
//                 id: 5457,
//                 code: "0113620                       ",
//                 model: "                    ",
//                 name: "",
//                 origin: "",
//                 sales_unit: "PZA   ",
//                 ref: "                    ",
//                 description: "CUBIERTERO LINEA TEN DE 900 MM                                                                                          ",
//                 slug: "0113620",
//                 stock: 18,
//                 views: 0,
//                 picture: null,
//                 price_1: "15.30",
//                 price_2: "17.00",
//                 price_3: "19.55",
//                 price_4: "24.44",
//                 price_5: "19.55",
//                 updated: "2018-05-17T22:32:14.646045-05:00",
//                 created_at: "2018-05-08T15:28:46.034386-05:00",
//                 img: "http://localhost:10500/media/sales/arts/base.jpg",
//                 active: false,
//                 featured: false,
//                 imported: false,
//                 is_shipping_required: false,
//                 item_type: 1,
//                 line: null,
//                 category: null,
//                 color: null,
//                 department: null,
//                 brand: 1,
//                 provider: null,
//                 sub_line: 173
//             },
//             {
//                 id: 5458,
//                 code: "0287120                       ",
//                 model: "                    ",
//                 name: "",
//                 origin: "",
//                 sales_unit: "PZA   ",
//                 ref: "                    ",
//                 description: "DB BASE P/PULSADOR SOBREPUESTO SISTEMA PUSH LARGO FITTINGS.                                                             ",
//                 slug: "0287120",
//                 stock: 739,
//                 views: 0,
//                 picture: null,
//                 price_1: "0.68",
//                 price_2: "0.75",
//                 price_3: "0.86",
//                 price_4: "1.08",
//                 price_5: "0.86",
//                 updated: "2018-05-17T22:32:14.646045-05:00",
//                 created_at: "2018-05-08T15:28:46.043243-05:00",
//                 img: "http://localhost:10500/media/sales/arts/base.jpg",
//                 active: false,
//                 featured: false,
//                 imported: false,
//                 is_shipping_required: false,
//                 item_type: 1,
//                 line: null,
//                 category: null,
//                 color: null,
//                 department: null,
//                 brand: 1,
//                 provider: null,
//                 sub_line: 173
//             },
//             {
//                 id: 5459,
//                 code: "0287620                       ",
//                 model: "                    ",
//                 name: "",
//                 origin: "",
//                 sales_unit: "PZA   ",
//                 ref: "                    ",
//                 description: "DB PULSADOR SOBREPUESTO SISTEMA PUSH LARGO FITTINGS.                                                                    ",
//                 slug: "0287620",
//                 stock: 698,
//                 views: 0,
//                 picture: null,
//                 price_1: "3.45",
//                 price_2: "4.16",
//                 price_3: "4.78",
//                 price_4: "5.98",
//                 price_5: "4.78",
//                 updated: "2018-05-17T22:32:14.646045-05:00",
//                 created_at: "2018-05-08T15:28:46.052304-05:00",
//                 img: "http://localhost:10500/media/sales/arts/base.jpg",
//                 active: false,
//                 featured: false,
//                 imported: false,
//                 is_shipping_required: false,
//                 item_type: 1,
//                 line: null,
//                 category: null,
//                 color: null,
//                 department: null,
//                 brand: 1,
//                 provider: null,
//                 sub_line: 173
//             },
//             {
//                 id: 5460,
//                 code: "0412720                       ",
//                 model: "                    ",
//                 name: "",
//                 origin: "",
//                 sales_unit: "PZA   ",
//                 ref: "                    ",
//                 description: "DB BASURERO 1 CUBO 12 LITROS                                                                                            ",
//                 slug: "0412720",
//                 stock: 5,
//                 views: 0,
//                 picture: null,
//                 price_1: "14.40",
//                 price_2: "16.00",
//                 price_3: "18.40",
//                 price_4: "23.00",
//                 price_5: "18.40",
//                 updated: "2018-05-17T22:32:14.646045-05:00",
//                 created_at: "2018-05-08T15:28:46.060766-05:00",
//                 img: "http://localhost:10500/media/sales/arts/base.jpg",
//                 active: false,
//                 featured: false,
//                 imported: false,
//                 is_shipping_required: false,
//                 item_type: 1,
//                 line: null,
//                 category: null,
//                 color: null,
//                 department: null,
//                 brand: 1,
//                 provider: null,
//                 sub_line: 173
//             },
//             {
//                 id: 5461,
//                 code: "0412820                       ",
//                 model: "                    ",
//                 name: "",
//                 origin: "",
//                 sales_unit: "PZA   ",
//                 ref: "                    ",
//                 description: "DB BASURERO 2 CUBOS C/FRENO 24 LITROS P/MUEBLE DE 450 MM.                                                               ",
//                 slug: "0412820",
//                 stock: 3,
//                 views: 0,
//                 picture: null,
//                 price_1: "139.50",
//                 price_2: "155.00",
//                 price_3: "178.25",
//                 price_4: "222.81",
//                 price_5: "178.25",
//                 updated: "2018-05-17T22:32:14.646045-05:00",
//                 created_at: "2018-05-08T15:28:46.069864-05:00",
//                 img: "http://localhost:10500/media/sales/arts/base.jpg",
//                 active: false,
//                 featured: false,
//                 imported: false,
//                 is_shipping_required: false,
//                 item_type: 1,
//                 line: null,
//                 category: null,
//                 color: null,
//                 department: null,
//                 brand: 1,
//                 provider: null,
//                 sub_line: 173
//             },
//             {
//                 id: 5462,
//                 code: "0426620                       ",
//                 model: "                    ",
//                 name: "",
//                 origin: "",
//                 sales_unit: "PZA   ",
//                 ref: "                    ",
//                 description: "DB MESA EXTENSIBLE TOPFLEX DE 810 MM                                                                                    ",
//                 slug: "0426620",
//                 stock: 3,
//                 views: 0,
//                 picture: null,
//                 price_1: "211.50",
//                 price_2: "235.00",
//                 price_3: "270.25",
//                 price_4: "337.81",
//                 price_5: "270.25",
//                 updated: "2018-05-17T22:32:14.646045-05:00",
//                 created_at: "2018-05-08T15:28:46.079710-05:00",
//                 img: "http://localhost:10500/media/sales/arts/base.jpg",
//                 active: false,
//                 featured: false,
//                 imported: false,
//                 is_shipping_required: false,
//                 item_type: 1,
//                 line: null,
//                 category: null,
//                 color: null,
//                 department: null,
//                 brand: 1,
//                 provider: null,
//                 sub_line: 173
//             },
//             {
//                 id: 5463,
//                 code: "0461791                       ",
//                 model: "                    ",
//                 name: "",
//                 origin: "",
//                 sales_unit: "PZA   ",
//                 ref: "                    ",
//                 description: "CESTO PARA ROPA EXTRAIBLE DE 450 MM C/FRENO SALICE                                                                      ",
//                 slug: "0461791",
//                 stock: 11,
//                 views: 0,
//                 picture: null,
//                 price_1: "100.80",
//                 price_2: "112.00",
//                 price_3: "128.80",
//                 price_4: "161.00",
//                 price_5: "128.80",
//                 updated: "2018-05-17T22:32:14.630415-05:00",
//                 created_at: "2018-05-08T15:28:46.088365-05:00",
//                 img: "http://localhost:10500/media/sales/arts/base.jpg",
//                 active: false,
//                 featured: false,
//                 imported: false,
//                 is_shipping_required: false,
//                 item_type: 1,
//                 line: null,
//                 category: null,
//                 color: null,
//                 department: null,
//                 brand: 1,
//                 provider: null,
//                 sub_line: 173
//             },
//             {
//                 id: 5464,
//                 code: "0461891                       ",
//                 model: "                    ",
//                 name: "",
//                 origin: "",
//                 sales_unit: "PZA   ",
//                 ref: "                    ",
//                 description: "CESTO PARA ROPA EXTRAIBLE DE 600 MM C/FRENO SALICE                                                                      ",
//                 slug: "0461891",
//                 stock: 10,
//                 views: 0,
//                 picture: null,
//                 price_1: "117.00",
//                 price_2: "130.00",
//                 price_3: "149.50",
//                 price_4: "186.88",
//                 price_5: "149.50",
//                 updated: "2018-05-17T22:32:14.630415-05:00",
//                 created_at: "2018-05-08T15:28:46.096933-05:00",
//                 img: "http://localhost:10500/media/sales/arts/base.jpg",
//                 active: false,
//                 featured: false,
//                 imported: false,
//                 is_shipping_required: false,
//                 item_type: 1,
//                 line: null,
//                 category: null,
//                 color: null,
//                 department: null,
//                 brand: 1,
//                 provider: null,
//                 sub_line: 173
//             },
//             {
//                 id: 5465,
//                 code: "0500168                       ",
//                 model: "                    ",
//                 name: "",
//                 origin: "",
//                 sales_unit: "JGO   ",
//                 ref: "                    ",
//                 description: "DB BASE METALICA PARA GOLA                                                                                              ",
//                 slug: "0500168",
//                 stock: 194,
//                 views: 0,
//                 picture: null,
//                 price_1: "2.25",
//                 price_2: "2.50",
//                 price_3: "2.88",
//                 price_4: "3.60",
//                 price_5: "2.88",
//                 updated: "2018-05-17T22:32:14.630415-05:00",
//                 created_at: "2018-05-08T15:28:46.105456-05:00",
//                 img: "http://localhost:10500/media/sales/arts/base.jpg",
//                 active: false,
//                 featured: false,
//                 imported: false,
//                 is_shipping_required: false,
//                 item_type: 1,
//                 line: null,
//                 category: null,
//                 color: null,
//                 department: null,
//                 brand: 1,
//                 provider: null,
//                 sub_line: 173
//             },
//             {
//                 id: 5466,
//                 code: "0502489                       ",
//                 model: "                    ",
//                 name: "",
//                 origin: "",
//                 sales_unit: "PZA   ",
//                 ref: "                    ",
//                 description: "JUEGO ESCURREPLATOS ACERO INOX DE 600 MM.                                                                               ",
//                 slug: "0502489",
//                 stock: 4,
//                 views: 0,
//                 picture: null,
//                 price_1: "27.90",
//                 price_2: "31.00",
//                 price_3: "35.65",
//                 price_4: "44.56",
//                 price_5: "35.65",
//                 updated: "2018-05-17T22:32:14.630415-05:00",
//                 created_at: "2018-05-08T15:28:46.115756-05:00",
//                 img: "http://localhost:10500/media/sales/arts/base.jpg",
//                 active: false,
//                 featured: false,
//                 imported: false,
//                 is_shipping_required: false,
//                 item_type: 1,
//                 line: null,
//                 category: null,
//                 color: null,
//                 department: null,
//                 brand: 1,
//                 provider: null,
//                 sub_line: 174
//             },
//             {
//                 id: 5467,
//                 code: "0502789                       ",
//                 model: "                    ",
//                 name: "",
//                 origin: "",
//                 sales_unit: "PZA   ",
//                 ref: "                    ",
//                 description: "JUEGO ESCURREPLATOS ACERO INOX DE 900 MM.                                                                               ",
//                 slug: "0502789",
//                 stock: 8,
//                 views: 0,
//                 picture: null,
//                 price_1: "36.90",
//                 price_2: "41.00",
//                 price_3: "47.15",
//                 price_4: "58.94",
//                 price_5: "47.15",
//                 updated: "2018-05-17T22:32:14.630415-05:00",
//                 created_at: "2018-05-08T15:28:46.124396-05:00",
//                 img: "http://localhost:10500/media/sales/arts/base.jpg",
//                 active: false,
//                 featured: false,
//                 imported: false,
//                 is_shipping_required: false,
//                 item_type: 1,
//                 line: null,
//                 category: null,
//                 color: null,
//                 department: null,
//                 brand: 1,
//                 provider: null,
//                 sub_line: 174
//             },
//             {
//                 id: 5468,
//                 code: "0502920                       ",
//                 model: "                    ",
//                 name: "",
//                 origin: "",
//                 sales_unit: "PZA   ",
//                 ref: "                    ",
//                 description: "BANDEJA BAJO FREGADERO ABS 862 X 541 MM 19 MM                                                                           ",
//                 slug: "0502920",
//                 stock: 27,
//                 views: 0,
//                 picture: null,
//                 price_1: "10.35",
//                 price_2: "11.50",
//                 price_3: "13.23",
//                 price_4: "16.54",
//                 price_5: "13.23",
//                 updated: "2018-05-17T22:32:14.630415-05:00",
//                 created_at: "2018-05-08T15:28:46.133662-05:00",
//                 img: "http://localhost:10500/media/sales/arts/base.jpg",
//                 active: false,
//                 featured: false,
//                 imported: false,
//                 is_shipping_required: false,
//                 item_type: 1,
//                 line: null,
//                 category: null,
//                 color: null,
//                 department: null,
//                 brand: 1,
//                 provider: null,
//                 sub_line: 174
//             },
//             {
//                 id: 5469,
//                 code: "0503020                       ",
//                 model: "                    ",
//                 name: "",
//                 origin: "",
//                 sales_unit: "PZA   ",
//                 ref: "                    ",
//                 description: "BANDEJA BAJO FREGADERO ABS 962 X 541 MM 19 MM                                                                           ",
//                 slug: "0503020",
//                 stock: 30,
//                 views: 0,
//                 picture: null,
//                 price_1: "12.60",
//                 price_2: "14.00",
//                 price_3: "16.10",
//                 price_4: "20.13",
//                 price_5: "16.10",
//                 updated: "2018-05-17T22:32:14.630415-05:00",
//                 created_at: "2018-05-08T15:28:46.143133-05:00",
//                 img: "http://localhost:10500/media/sales/arts/base.jpg",
//                 active: false,
//                 featured: false,
//                 imported: false,
//                 is_shipping_required: false,
//                 item_type: 1,
//                 line: null,
//                 category: null,
//                 color: null,
//                 department: null,
//                 brand: 1,
//                 provider: null,
//                 sub_line: 174
//             },
//             {
//                 id: 5470,
//                 code: "0615501                       ",
//                 model: "                    ",
//                 name: "",
//                 origin: "",
//                 sales_unit: "PZA   ",
//                 ref: "                    ",
//                 description: "DESLIZADOR AJUSTABLE DE 6X17 MM. BLANCO                                                                                 ",
//                 slug: "0615501",
//                 stock: -95,
//                 views: 0,
//                 picture: null,
//                 price_1: "0.16",
//                 price_2: "0.18",
//                 price_3: "0.21",
//                 price_4: "0.26",
//                 price_5: "0.21",
//                 updated: "2018-05-17T22:32:14.630415-05:00",
//                 created_at: "2018-05-08T15:28:46.152002-05:00",
//                 img: "http://localhost:10500/media/sales/arts/base.jpg",
//                 active: false,
//                 featured: false,
//                 imported: false,
//                 is_shipping_required: false,
//                 item_type: 1,
//                 line: null,
//                 category: null,
//                 color: null,
//                 department: null,
//                 brand: 1,
//                 provider: null,
//                 sub_line: 124
//             },
//             {
//                 id: 5471,
//                 code: "0616887                       ",
//                 model: "                    ",
//                 name: "",
//                 origin: "",
//                 sales_unit: "JGO   ",
//                 ref: "                    ",
//                 description: "DB BASE PLASTICA PARA GOLA                                                                                              ",
//                 slug: "0616887",
//                 stock: 181,
//                 views: 0,
//                 picture: null,
//                 price_1: "0.59",
//                 price_2: "0.65",
//                 price_3: "0.75",
//                 price_4: "0.94",
//                 price_5: "0.75",
//                 updated: "2018-05-17T22:32:14.614795-05:00",
//                 created_at: "2018-05-08T15:28:46.161065-05:00",
//                 img: "http://localhost:10500/media/sales/arts/base.jpg",
//                 active: false,
//                 featured: false,
//                 imported: false,
//                 is_shipping_required: false,
//                 item_type: 1,
//                 line: null,
//                 category: null,
//                 color: null,
//                 department: null,
//                 brand: 1,
//                 provider: null,
//                 sub_line: 173
//             }
//         ]
//     },
//     categories: {
//         count: 4,
//         next: null,
//         previous: null,
//         results: [
//             {
//                 id: 1,
//                 background: "http://localhost:10500/media/sales/department/2018/03/09/img-base-l_7TLAQQE.png",
//                 description: "<p>Categor&iacute;a de articulos.</p>",
//                 img: "http://localhost:10500/media/sales/department/2018/03/09/img-base-m_2PaiR9c.png",
//                 name: "Cantos",
//                 slug: "cantos",
//                 code: "",
//                 order: 4
//             },
//             {
//                 id: 2,
//                 background: "http://localhost:10500/media/sales/department/2018/03/09/img-base-l_1FaGtUF.png",
//                 description: "<p>Categor&iacute;a de productos</p>",
//                 img: "http://localhost:10500/media/sales/department/2018/03/09/img-base-m_6Az0v5K.png",
//                 name: "Sobre",
//                 slug: "sobre",
//                 code: "",
//                 order: 3
//             },
//             {
//                 id: 3,
//                 background: "http://localhost:10500/media/sales/department/2018/03/09/img-base-l_pJy3t71.png",
//                 description: "<p>Categor&iacute;a de productos.</p>",
//                 img: "http://localhost:10500/media/sales/department/2018/03/09/img-base-m_C0Fz6nr.png",
//                 name: "Laminas",
//                 slug: "laminas",
//                 code: "",
//                 order: 2
//             },
//             {
//                 id: 4,
//                 background: "http://localhost:10500/media/sales/department/2018/03/09/img-base-l_7waahJS.png",
//                 description: "<p>Categor&iacute;a de productos</p>",
//                 img: "http://localhost:10500/media/sales/department/2018/03/09/img-base-m_sfJRBiZ.png",
//                 name: "Herrajes",
//                 slug: "herrajes",
//                 code: "",
//                 order: 1
//             }
//         ]
//     },
//     testimonials: [
//         {
//             id: 1,
//             name: 'Josmer Hernández',
//             company: 'Dev2tech',
//             description: `<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
//             incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation 
//             ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit 
//             in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat 
//             non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>`,
//             img_url: 'https://images.pexels.com/photos/1190446/pexels-photo-1190446.jpeg?auto=compress&cs=tinysrgb',
//         },
//         {
//             id: 2,
//             name: 'Juan Perez',
//             company: 'Dev2tech',
//             description: `<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
//             incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation 
//             ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit 
//             in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat 
//             non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>`,
//             img_url: 'https://images.pexels.com/photos/1190446/pexels-photo-1190446.jpeg?auto=compress&cs=tinysrgb',
//         },
//     ],
//     blog_post: {
//         count: 5,
//         next: null,
//         previous: null,
//         results: [
//             {
//                 id: 2,
//                 title: "Segundo post",
//                 sub_title: "Segundo post",
//                 text: "<p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Non quisquam numquam perferendis earum sit error quae ad blanditiis at, corporis assumenda, rerum magnam explicabo est, pariatur adipisci sapiente deserunt soluta?</p>\r\n\r\n<p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Non quisquam numquam perferendis earum sit error quae ad blanditiis at, corporis assumenda, rerum magnam explicabo est, pariatur adipisci sapiente deserunt soluta?</p>\r\n\r\n<p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Non quisquam numquam perferendis earum sit error quae ad blanditiis at, corporis assumenda, rerum magnam explicabo est, pariatur adipisci sapiente deserunt soluta?</p>\r\n\r\n<p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Non quisquam numquam perferendis earum sit error quae ad blanditiis at, corporis assumenda, rerum magnam explicabo est, pariatur adipisci sapiente deserunt soluta?</p>",
//                 is_public: true,
//                 draft: false,
//                 published: "2018-04-30",
//                 read_time: 0,
//                 updated: "2018-04-30T14:45:57.713691-05:00",
//                 created_at: "2018-02-16T05:41:19.508734-06:00",
//                 img: "http://localhost:10500/media/blog/post/2018/03/09/img-base-m_PeQpAFm.png",
//                 background: "http://localhost:10500/media/blog/post/2018/03/09/img-base-l_hftXERS.png",
//                 slug: "segundo-post",
//                 author: 1,
//                 updated_by: 1
//             },
//             {
//                 id: 3,
//                 title: "Tercer post",
//                 sub_title: "Tercer post",
//                 text: "<p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Non quisquam numquam perferendis earum sit error quae ad blanditiis at, corporis assumenda, rerum magnam explicabo est, pariatur adipisci sapiente deserunt soluta?</p>\r\n\r\n<p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Non quisquam numquam perferendis earum sit error quae ad blanditiis at, corporis assumenda, rerum magnam explicabo est, pariatur adipisci sapiente deserunt soluta?</p>\r\n\r\n<p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Non quisquam numquam perferendis earum sit error quae ad blanditiis at, corporis assumenda, rerum magnam explicabo est, pariatur adipisci sapiente deserunt soluta?</p>\r\n\r\n<p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Non quisquam numquam perferendis earum sit error quae ad blanditiis at, corporis assumenda, rerum magnam explicabo est, pariatur adipisci sapiente deserunt soluta?</p>",
//                 is_public: false,
//                 draft: true,
//                 published: "2018-03-09",
//                 read_time: 0,
//                 updated: "2018-03-09T12:25:00.536148-06:00",
//                 created_at: "2018-02-16T05:42:31.745621-06:00",
//                 img: "http://localhost:10500/media/blog/post/2018/03/09/img-base-m_rhRpiqX.png",
//                 background: "http://localhost:10500/media/blog/post/2018/03/09/img-base-l_I73DSZC.png",
//                 slug: "tercer-post",
//                 author: 1,
//                 updated_by: 1
//             },
//             {
//                 id: 1,
//                 title: "Moby Supply",
//                 sub_title: "Moby Supply",
//                 text: "<p>Primer post</p>",
//                 is_public: false,
//                 draft: false,
//                 published: "2018-04-23",
//                 read_time: null,
//                 updated: "2018-04-23T19:20:30.094361-05:00",
//                 created_at: "2018-02-27T09:46:14.623000-06:00",
//                 img: "http://localhost:10500/media/blog/post/2018/03/09/img-base-m_1pk65wq.png",
//                 background: "http://localhost:10500/media/blog/post/2018/03/09/img-base-l_bRXZoey.png",
//                 slug: "moby-supply",
//                 author: 1,
//                 updated_by: 1
//             },
//             {
//                 id: 4,
//                 title: "Moby Supply",
//                 sub_title: "Moby",
//                 text: "<p>Moby supply</p>",
//                 is_public: true,
//                 draft: false,
//                 published: "2018-04-23",
//                 read_time: 2,
//                 updated: "2018-04-23T19:17:06.465637-05:00",
//                 created_at: "2018-03-08T04:54:08.377943-06:00",
//                 img: "http://localhost:10500/media/blog/post/2018/03/09/img-base-m.png",
//                 background: "http://localhost:10500/media/blog/post/2018/03/09/img-base-l.png",
//                 slug: "moby-supply-1",
//                 author: 1,
//                 updated_by: 1
//             },
//             {
//                 id: 5,
//                 title: "GeoChart color example",
//                 sub_title: "Segundo post",
//                 text: "Content",
//                 is_public: true,
//                 draft: false,
//                 published: "2018-08-27",
//                 read_time: 20,
//                 updated: "2018-08-27T22:55:51.203801-05:00",
//                 created_at: "2018-08-27T22:55:51.203801-05:00",
//                 img: null,
//                 background: null,
//                 slug: "q7",
//                 author: 6,
//                 updated_by: 6
//             }
//         ]
//     },
//     pages:{
//         count: 6,
//         next: null,
//         previous: null,
//         results: [
//             {
//                 id: 1,
//                 name: "inicio",
//                 description: "",
//                 have_icon: false,
//                 url: "/"
//             },
//             {
//                 id: 2,
//                 name: "servicios",
//                 description: "",
//                 have_icon: false,
//                 url: "/servicios"
//             },
//             {
//                 id: 3,
//                 name: "productos",
//                 description: "",
//                 have_icon: false,
//                 url: "/productos"
//             },
//             {
//                 id: 4,
//                 name: "blog",
//                 description: "",
//                 have_icon: false,
//                 url: "/blog"
//             },
//             {
//                 id: 5,
//                 name: "contacto",
//                 description: "",
//                 have_icon: false,
//                 url: "/contacto"
//             },
//             {
//                 id: 6,
//                 name: "search",
//                 description: "",
//                 have_icon: true,
//                 url: "/busqueda"
//             }
//         ]
//     },
//     page_position:{
//         count: 3,
//         next: null,
//         previous: null,
//         results: [
//             {
//                 id: 1,
//                 name: "header",
//                 description: ""
//             },
//             {
//                 id: 2,
//                 name: "section",
//                 description: ""
//             },
//             {
//                 id: 3,
//                 name: "footer",
//                 description: ""
//             }
//         ]
//     }
// }

// var _ = {services: [
//         {
//                 id:1,
//                 name:'Canteo',
//         title: "Canteo",
//         content: `<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
//         incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation 
//         ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit 
//         in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat 
//         non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>`,
//         image: "http://localhost:10500/media/sales/service/2018/03/09/img-base-m.png",
//         slug: "canteo",
//         background: "http://localhost:10500/media/sales/service/2018/03/09/img-base-l.png",
//         featured:true,
//     },
//     {
//         id: 2,
//         name:'Cortes',
//         title: "Cortes",
//         content: `<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
//         incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation 
//         ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit 
//         in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat 
//         non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>`,
//         image: "http://localhost:10500/media/sales/service/2018/03/09/img-base-m.png",
//         slug: "cortes",
//         background: "http://localhost:10500/media/sales/service/2018/03/09/img-base-l.png",
//         featured:true,
//     },
//     {
//         id: 3,
//         name:'Perforacion',
//         title: "Perforación",
//         content: `<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
//         incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation 
//         ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit 
//         in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat 
//         non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>`,
//         image: "http://localhost:10500/media/sales/service/2018/03/09/img-base-m.png",
//         slug: "perforacion",
//         background: "http://localhost:10500/media/sales/service/2018/03/09/img-base-l.png",
//         featured:true,
//     },
//     {
//         id: 4,
//         name:'Fraseo',
//         title: "Fraseo",
//         content: `<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
//         incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation 
//         ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit 
//         in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat 
//         non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>`,
//         image: "http://localhost:10500/media/sales/service/2018/03/09/img-base-m.png",
//         slug: "fraseo",
//         background: "http://localhost:10500/media/sales/service/2018/03/09/img-base-l.png",
//         featured:false,
//     },
//     {
//             id: 5,
//             name:'Fraseos',
//             title: "Fraseo",
//             content: `<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
//             incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation 
//             ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit 
//             in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat 
//         non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>`,
//         image: "http://localhost:10500/media/sales/service/2018/03/09/img-base-m.png",
//         slug: "fraseo",
//         background: "http://localhost:10500/media/sales/service/2018/03/09/img-base-l.png",
//         featured:false,
//     }
// ],
// categories: [
//     {
//         id: 1,
//         background: "http://localhost:10500/media/sales/department/2018/03/09/img-base-l_7TLAQQE.png",
//         description: "<p>Categor&iacute;a de articulos.</p>",
//         img: "http://localhost:10500/media/sales/department/2018/03/09/img-base-m_2PaiR9c.png",
//         name: "Cantos",
//         slug: "cantos",
//         code: "",
//         order: 4
//     },
//     {
//         id: 2,
//         background: "http://localhost:10500/media/sales/department/2018/03/09/img-base-l_1FaGtUF.png",
//         description: "<p>Categor&iacute;a de productos</p>",
//         img: "http://localhost:10500/media/sales/department/2018/03/09/img-base-m_6Az0v5K.png",
//         name: "Sobre",
//         slug: "sobre",
//         code: "",
//         order: 3
//     },
//     {
//         id: 3,
//         background: "http://localhost:10500/media/sales/department/2018/03/09/img-base-l_pJy3t71.png",
//         description: "<p>Categor&iacute;a de productos.</p>",
//         img: "http://localhost:10500/media/sales/department/2018/03/09/img-base-m_C0Fz6nr.png",
//         name: "Laminas",
//         slug: "laminas",
//         code: "",
//         order: 2
//     },
//     {
//         id: 4,
//         background: "http://localhost:10500/media/sales/department/2018/03/09/img-base-l_7waahJS.png",
//         description: "<p>Categor&iacute;a de productos</p>",
//         img: "http://localhost:10500/media/sales/department/2018/03/09/img-base-m_sfJRBiZ.png",
//         name: "Herrajes",
//         slug: "herrajes",
//         code: "",
//         order: 1
//     },
//     {
//         id: 5,
//         background: "http://localhost:10500/media/sales/department/2018/03/09/img-base-l_7waahJS.png",
//         description: "<p>Categor&iacute;a de productos</p>",
//         img: "http://localhost:10500/media/sales/department/2018/03/09/img-base-m_sfJRBiZ.png",
//         name: "Herrajes",
//         slug: "herrajes",
//         code: "",
//         order: 1
//     },
//     {
//         id: 6,
//         background: "http://localhost:10500/media/sales/department/2018/03/09/img-base-l_7waahJS.png",
//         description: "<p>Categor&iacute;a de productos</p>",
//         img: "http://localhost:10500/media/sales/department/2018/03/09/img-base-m_sfJRBiZ.png",
//         name: "Herrajes",
//         slug: "herrajes",
//         code: "",
//         order: 1
//     }
// ],
// };